language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run build
before_deploy:
  - cp README.md dist/
  - if [ $CNAME ]; then
      echo $CNAME > dist/CNAME;
    fi
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    keep_history: false
    local_dir: dist
    on:
      branch: master
      # condition: $GITHUB_TOKEN IS present
      condition: $GITHUB_TOKEN
